// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "shopimage":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............ccccccccccccccccccccccccccccccc....
............cccccceeeeeeeeeeeeeeeeeeeeecccccc...
............ccccceeceeeeeeeeceeeeeeeeceeccccc...
............cccceec7ceeeeeec4ceeeeeec6ceecccc...
............ccceec767ceeeec424ceeeec686ceeccc...
............cccec76667ceec42224ceec68886ceccc...
............ccceec767ceeeec424ceeeec686ceeccc...
............cccceec7ceeeeeec4ceeeeeec6ceecccc...
............ccccceeceeeeeeeeceeeeeeeeceeccccc...
............cccccceeeeeeeeeeeeeeeeeeeeecccccc...
.............ccccccccccccccccccccccccccccccc....
...............ccccc.................ccccc......
................ccc....ccccccccc......ccc.......
.................cc...ccfccefeecc.....cc........
.................cc..ccfffefffeec.....cc........
.................cc..cffffeffffec.....cc........
.................cc..cfffffffffcc.....cc........
.................cc..cff1fff1ffec.....cc........
.................cc..cf1f1f1f1fcc.....cc........
.................cc..cfffffffffc......cc........
.................cc..cfff1f1fffc......cc........
.................cc..cffff1ffffc......cc........
.................cc..ccfffffffcc......cc........
.................cc..cccbdddbbbcc.....cc........
.................cc..c2bbddd2bbbc.....cc........
.................cc..c2bb2d222bbc.....cc........
................cccccccbbcccccccccccccccc.......
...............cccceeeebbeeeeeeeeeeeeecccc......
...............ccceeeeeebeeeeeeeeeeeeeeccc......
...............cceecccceceeceecccceccceecc......
...............ceeeceeeeceeceeceecececeeec......
...............ccceceeeeceeceeceececececcc......
...............ceeeceeeecccceeceececcceeec......
...............ceeecccceceeceeceececeeeeec......
...............ccceeeececeeceeceecececcccc......
...............ceeeeeececeeceeceececeeeeec......
...............cceecccceceeceecccceceeeecc......
...............ccceeeeeeeeeeeeeeeeeeeeeccc......
...............cccceeeeeeeeeeeeeeeeeeecccc......
`;
            case "image2":
            case "Made-by-LUCAS-M":return img`
..cccccccccccccccccccccccccccccccccccccc........
.ccffffffffffffffffffffffffffffffffffffcc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.cffffffffffffffffffffffffffffffffffffffc.......
.ccffffffffffffffffffffffffffffffffffffcc.......
..cccccccccccccccccccccccccccccccccccccc........
.....ccc666bbbbcc.......cccccccccccc............
..cccccccccccccccccc....cccccccccccc............
.ccffffffffffffffffcc...ccccc66ccccc............
.cffffffffffffffffffc...cccc6666cccc............
.cffffffffffffffffffc...cc66666666cc............
.cffffffffffffffffffc...c6666666666c............
.cffffffffffffffffffc...c6666666666c............
.cffffffffffffffffffc...c6666666666c............
.cffffffffffffffffffc...c6666666666c............
.cffffffffffffffffffc...c66b6b66666c............
.cffffffffffffffffffc...c66bbb6b666c............
.cffffffffffffffffffc...cb6bbbbb66bc............
.cffffffffffffffffffc...cbbbbbbbb6bc............
.ccffffffffffffffffcc...cbbbbbbbbbbc............
..cccccccccccccccccc....cbbbbbbbbbbc............
....ccccc666ccccc.......cbbbbbbbbbbc............
..ccccccccccccccccccccccccccccccccccccccccccccc.
.ccfffffffffffffffffffffffffffffffffffffffffffcc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.cfffffffffffffffffffffffffffffffffffffffffffffc
.ccfffffffffffffffffffffffffffffffffffffffffffcc
..ccccccccccccccccccccccccccccccccccccccccccccc.
.....ccc6666666ccc....cccccc666666cccccc........
.....c66666bb6666c....ccc66666b6b6666ccc........
.....cbbbbbbb66bbc....c666bbb6bbbbb6666c........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
